name: "Canvas: Mark-As Done Script"
description: "Update Canvas module item completion requirements for courses"
title: "Canvas: Mark-As Done"
labels:
  - automation
  - canvas
  - module-completion
body:
  - type: markdown
    attributes:
      value: |
        ## Add a job title

        Add the Course title or ID to name this job.

  - type: dropdown
    id: environment
    attributes:
      label: "Canvas Environment"
      description: "Select the Canvas environment you want to update. NOTE: Updating Prod will be a student/partner-facing action."
      options:
        - "Canvas Beta"
        - "Canvas Prod (student-facing)"
      default: 0
    validations:
      required: true

  - type: input
    id: course_ids
    attributes:
      label: "Course ID or IDs"
      description: "Enter a single Course ID, or a comma-separated list of Course IDs. The Course ID can be found in the Canvas URL of the course or courses you want updated."
      placeholder: "e.g., 39005, 39006, 45966, 27199"
    validations:
      required: true

  - type: checkboxes
    id: prod_confirmation
    attributes:
      label: "ATTENTION!"
      options:
        - label: 'If the PROD is checked above, I acknowledge that this action will update production pages in Canvas'
          required: false
