name: "Canvas: Add Video Run Time"
description: "GitHub Job Name* (Required) : Enter a descriptive program or course name between the parentheses. REQUIRED. The unique identifier for this update job."
title: "Canvas: Video Run Times (e.g., Fordham Law)"
labels:
  - update-wistia-page-titles
body:
  - type: markdown
    attributes:
      value: |
        ℹ️ **GitHub Job Name** (Required): Enter a descriptive program or course name between the parentheses. **Example:** Canvas: Video Run Times (e.g., Fordham Law)

  - type: dropdown
    id: environment
    attributes:
      label: "Select Canvas Environment"
      description: "Which Environment in Canvas? 'PROD' updates live courses. 'BETA' updates the testing environment."
      options:
        - "BETA"
        - "PROD"
      default: 0
    validations:
      required: true

  - type: dropdown
    id: update_pages_for
    attributes:
      label: "Specify Course Scope"
      options:
        - "Entire Program"
        - "Specific Course(s) Only"
    validations:
      required: true

  - type: input
    id: course_ids
    attributes:
      label: "Account ID or Course ID(s)"
      description: |
        For "Entire Program", enter the desired Account ID. For "Course(s) Only", enter the Course ID(s).

        ℹ️ *Note:*

        **For Entire Program**: Find the Account ID in the URL: `digitalcampus.instructure.com/accounts/[Account_ID]` (e.g., `192` from `.../accounts/192`)

        **For Specific Course(s) Only**: Find the Course ID in the URL: `digitalcampus.instructure.com/courses/[Course_ID]` (e.g., `54278` from `.../courses/54278`)
      placeholder: "e.g., 192 or 39005, 39006, 459"
    validations:
      required: true

  - type: checkboxes
    id: module_rollup
    attributes:
      label: "Module Roll-Up Options"
      options:
        - label: "Include updating Module Roll-Up"
          required: false

  - type: checkboxes
    id: prod_confirmation
    attributes:
      label: "ATTENTION: PRODUCTION CONFIRMATION"
      options:
        - label: 'I acknowledge that by checking "PROD" above, this action will update live production pages in Canvas.'
          required: true
